package com.twu.biblioteca;

import com.twu.biblioteca.views.UI_GLOBALS;

public class UI_TEST_GLOBALS {
    public static final String LOGGED_IN_USER_NAVIGATION_BAR_STRING = "Navigation Bar:" + UI_GLOBALS.LINE_BREAK +
            "[a] "+ UI_GLOBALS.NAVIGATION_BAR_LABELS_ACCOUNT_INFO + UI_GLOBALS.LINE_BREAK +
            "[b] " + UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_BOOKS +UI_GLOBALS.LINE_BREAK +
            "[rb] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_RETURN_BOOKS+UI_GLOBALS.LINE_BREAK +
            "[m] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_MOVIES+UI_GLOBALS.LINE_BREAK +
            "[rm] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_RETURN_MOVIES+UI_GLOBALS.LINE_BREAK +
            "[lo] "+ UI_GLOBALS.NAVIGATION_BAR_USER_LOG_OUT_LABEL + UI_GLOBALS.LINE_BREAK +
            "[x] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_QUIT_BIBLIOTECA+UI_GLOBALS.LINE_BREAK;
    public static final String LOGGED_OUT_USER_NAVIGATION_BAR = "Navigation Bar:" + UI_GLOBALS.LINE_BREAK +
            "[a] "+ UI_GLOBALS.NAVIGATION_BAR_LABELS_ACCOUNT_INFO +UI_GLOBALS.LINE_BREAK +
            "[b] " + UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_BOOKS +  UI_GLOBALS.LINE_BREAK +
            "[m] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_MOVIES+ UI_GLOBALS.LINE_BREAK +
            "[li] "+ UI_GLOBALS.NAVIGATION_BAR_LOG_IN_LABEL + UI_GLOBALS.LINE_BREAK +
            "[x] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_QUIT_BIBLIOTECA+UI_GLOBALS.LINE_BREAK
            ;

}
