package com.twu.biblioteca;

import com.twu.biblioteca.views.UI_GLOBALS;

public class UI_TEST_GLOBALS {
    public static final String NAVIGATION_BAR_STRING = "Navigation Bar:  [h] "+ UI_GLOBALS.NAVIGATION_BAR_LABELS_MAIN_MENU +" [b] " + UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_BOOKS +" [rb] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_RETURN_BOOKS+" [m] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_BROWSE_MOVIES+" [x] "+UI_GLOBALS.NAVIGATION_BAR_LABELS_QUIT_BIBLIOTECA+" \n";
}
